#**************************************************************
# This .sdc file is created by Terasic Tool.
# Users are recommended to modify this file to match users logic.
#**************************************************************

# Clock to output delay
# Maximum
set Max_Tco_phy 9.0
# Minimum
set Min_Tco_phy 0.0

# Setup time
set Tsu_phy 6.00

# Hold time
set Th_phy 0

#**************************************************************
# Board trace delay (Following should be updated based on actual board delays.)
#**************************************************************
# Board delay from PHY to FPGA
set Max_phy2fpga 0
set Min_phy2fgpa 0

# Board delay from FPGA to PHY
set Max_fpga2phy 0
set Min_fpga2phy 0

# Delay from clock to FPGA. (This has been considered same as other pins from PHY to FPGA delay.)
set Max_clk2fpga 0
set Min_clk2fpga 0

# Delay from clock to PHY. (60 MHz clock is being generated by PHY chip. Hence we have considered 0 here.)
set Max_clk2phy 0
set Min_clk2phy 0

#**************************************************************
# Create Clock
#**************************************************************
create_clock -name {usb_clk60} -period "60.0 MHz" [get_ports usb_clk60]

# for enhancing USB BlasterII to be reliable, 25MHz
create_clock -name {altera_reserved_tck} -period 40 {altera_reserved_tck}
set_input_delay -clock altera_reserved_tck -clock_fall 3 [get_ports altera_reserved_tdi]
set_input_delay -clock altera_reserved_tck -clock_fall 3 [get_ports altera_reserved_tms]
set_output_delay -clock altera_reserved_tck 3 [get_ports altera_reserved_tdo]

#**************************************************************
# Create Generated Clock
#**************************************************************
derive_pll_clocks



#**************************************************************
# Set Clock Latency
#**************************************************************



#**************************************************************
# Set Clock Uncertainty
#**************************************************************
derive_clock_uncertainty



#**************************************************************
# Set Input Delay
#**************************************************************
set_input_delay -clock { usb_clk60 } \
                 -max  [expr $Max_Tco_phy + $Max_phy2fpga + $Max_clk2phy - $Min_clk2fpga ] \
                       [get_ports { usb_ulpi_dir \
                                    usb_ulpi_nxt \
                                    usb_ulpi_data[*] } ]

set_input_delay -clock { usb_clk60 } \
                -min   [expr $Min_Tco_phy + $Min_phy2fgpa + $Min_clk2phy - $Max_clk2fpga ] \
                       [get_ports { usb_ulpi_dir \
                                    usb_ulpi_nxt \
                                    usb_ulpi_data[*] } ]

#**************************************************************
# Set Output Delay
#**************************************************************
set_output_delay -clock { usb_clk60 } \
                 -max   [expr $Tsu_phy + $Max_fpga2phy + $Max_clk2fpga - $Min_clk2phy ] \
                        [get_ports { usb_ulpi_stp \
                                     usb_ulpi_data[*] } ]

set_output_delay -clock { usb_clk60 } \
                 -min   [expr -$Th_phy + $Min_fpga2phy + $Min_clk2fpga - $Max_clk2phy ] \
                        [get_ports { usb_ulpi_stp \
                                     usb_ulpi_data[*] } ]

#**************************************************************
# Set Clock Groups
#**************************************************************



#**************************************************************
# Set False Path
#**************************************************************



#**************************************************************
# Set Multicycle Path
#**************************************************************



#**************************************************************
# Set Maximum Delay
#**************************************************************



#**************************************************************
# Set Minimum Delay
#**************************************************************



#**************************************************************
# Set Input Transition
#**************************************************************



#**************************************************************
# Set Load
#**************************************************************



